### ISSUE TITLE
SVDDNeg fallback test broken

### ISSUE THREAD

**Issue by holtri** [englhardt/SVDD.jl#2]
Test of SVDDNeg fallback to VanillaSVDD is broken after upgrade to JuMP 0.19 but only with Ipopt. Test succeeds locally with Gurobi solver.

https://github.com/englhardt/SVDD.jl/blob/abda6732e68a2f34ad8358285de6167e0bc797af/test/classifiers/classifier_svdd_neg_test.jl#L42

**Comment by englhardt** [comment]
Fixed in #16.
